openapi: 3.0.3
info:
  title: Swagger Student
  description: Manage Student.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  /users:
    $ref: "./user/CreateUser.yaml"
  /login:
    $ref: "./user/Login.yaml"
  /students:
    $ref: "./student/CreateStudent.yaml"
  /students/{page}:
    $ref: "./student/GetAllStudent.yaml"